### ISSUE TITLE
Improvement - Add link to wiki for units

### ISSUE THREAD

**Issue by Indigo744** [lyrgard/ffbeEquip#122]
Hello!

First of all, love your work. Thanks a lot for building it.

I have a small suggestion to improve this tool: **add a link to the wiki for the units, just like the one for the equipment.**

I find myself a lot in the need to go look to the unit's ability, and I have to open another page, go to the wiki, search by unit name, and at last see the unit...

Currently for an equipment, the blue arrow will lead you to the wiki page:
![image](https://user-images.githubusercontent.com/7137528/43716667-3ddf5af2-9985-11e8-9671-3ed2540b3b43.png)

It could be very cool if we could have the same thing for the unit tile, for instance after the name:
![image](https://user-images.githubusercontent.com/7137528/43716696-60e09aac-9985-11e8-8da6-2393119d5f1f.png)

Thanks!

If you think it's a good improvement, I may find some time to submit a PR, if you want.

**Comment by tomurderthelight** [comment]
i think the wiki links for units are almost anywhere units are -except- on the units page.
* once you select a unit, there is a 'unit info' link on the builder page
* the unit search page has wiki links next to the unit names.

**Comment by Indigo744** [comment]
Yup, you're right. But I would still like to have it in the units page.

See the submitted PR.

**Comment by lyrgard** [comment]
Thanks for the correction in the PR, @Indigo744  !

Also, units now have a fixed width case, so it will be prettier !

**Comment by Indigo744** [comment]
Perfect! Thank you 😺
