### ISSUE TITLE
Pinning an Item-World-enchanted weapon pins the unenchanted version

### ISSUE THREAD

**Issue by thailyn** [lyrgard/ffbeEquip#129]
Say I have a unit in the builder and he has an item equipped that was enchanted in the Item World.  If I pin that item, the item is replaced with the "normal," unenchanted item.  The unit's stats are updated to reflect this change.  If I first pin the weapon and then manually change it, I can change it to the enchanted version, and that is correctly pinned (same if I manually apply a custom enchantment to the normal version).  So the only issue is that the act of pinning replaces the item with the unenchanted version.

**Comment by lyrgard** [comment]
Fixed. Thanks @biovenger
