### ISSUE TITLE
Contribute tab does not indicate success

### ISSUE THREAD

**Issue by thailyn** [lyrgard/ffbeEquip#161]
I was trying to use the Contribute tab to indicate that the max copies for the materia "光属性耐性+20%" in JP is now at least two (I had one already and just got one in the FFVII event), but I'm not sure if the correction was successfully submitted.  The instruction on the page say the page will reload if "the save is successful," but the page never reloads for me, nor does it give any error messages.

My only idea is that the AJAX request in the [sendToServer](https://github.com/lyrgard/ffbeEquip/blob/5c62837eb91fa4bc3d1542ff8b632a3b80b96e22/static/contribute.js#L154) function never receives a response, but I'm not going to pretend to know how AJAX and more fancy web programming techniques work.  I'd be happy to help debug, though.  I see this behavior in Waterfox 56.2.2 and Chrome 68 on Windows 10.

**Comment by Indigo744** [comment]
Should be fixed when PR #202 land. Thanks for reporting!
