### ISSUE TITLE
JP - Yuna 7* EVO MAG Stat

### ISSUE THREAD

**Issue by Darwe-Canine** [lyrgard/ffbeEquip#162]
This issue has been intermittently reproduced when selecting "All Equipment", and consistently when selecting "Only Owned Equipment" with an empty equipment list.

On JP side, select Yuna 7* (EVO MAG Stat = 100), pin EVO MAG +10% (EVO MAG Stat goes to 110), then build for Spirit, and EVO MAG drops to 100. Removing and re-pinning EVO MAG +10 returns the EVO MAG Stat to 110 as expected.

**Comment by lyrgard** [comment]
Corrected. It was the "try to do it with less slots" feature that was removing the Evo MAG +10% as it didn't participate to the goal. It won't try to remove pinned items now.
