### ISSUE TITLE
The search field on the inventory page does not search both JP and GL names.

### ISSUE THREAD

**Issue by thailyn** [lyrgard/ffbeEquip#171]
If I am looking at the Inventory tab for the JP server, there is a search box that filters items/materia on the page.  The search behavior is inconsistent, and depends on what languages are set for an item's name.  If the item has only a Japanese name, that name is searched.  However, if the item has both an English and Japanese name, only the English name is searched.

Example: I just finished the FFIII rerun event, and that gave a "水属性耐性+15%" materia ("Water Resistance +15%").  When I enter "水" into the materia subpage's search field, I only get two results, "水底の悪魔" and "英雄の誓い・水".  Both of these materia do not have an English translation.  When I do a normal browser Ctrl+F search on the page, I get eight results.  The other six matches have English translations.

Similarly, searching for "オニオ" in the search box on the equipment subtab only shows Onion Knight's STMR, "オニオンブレード", which does not have an English translation.  The other four Onion Knight items do not show up. (Searching for "Onion" gives all of these plus Lulu's TMR, which uses "タマネギ" in the Japanese item name (the Japanese word for "onion"), instead of the transliteration "オニオン".

**Comment by lyrgard** [comment]
Corrected ! Thanks for reporting !
