### ISSUE TITLE
Not being able to sign in

### ISSUE THREAD

**Issue by Zeromaster0** [lyrgard/ffbeEquip#180]
I was signing on to the FFBE Equip website and as I sign in like I usually do it would stop after putting in my Google info this error would pop up.
{"statusCode":400,"error":"Bad Request","message":"Error validating request query. \"scope\" is not allowed."} 

It would not let me go past that. And when I tried another Google account the same error would pop up.

**Comment by lyrgard** [comment]
Google slightly changed their API, and as it is a security matter, I'm very strict about it, so it made the validation test fail. I updated my server to reflect their change, it is OK now.

Thanks for reporting !

**Comment by Indigo744** [comment]
@Zeromaster0 can you close this issue if it is resolved? Thanks!

**Comment by Darwe-Canine** [comment]
This can be closed.
