### ISSUE TITLE
Suggestion: Simulate BiS IW Enchants during build

### ISSUE THREAD

**Issue by because-bot-fed** [lyrgard/ffbeEquip#184]
Checkbox or something to let you have the builder pretend you had various enchants (Probably easiest to keep it simple and assume "best" outcomes on IW enchants, rare enchants and 15/12/10% combos) while building, since this would likely create gear options/combinations where you could use a weapon with an element, or killer, instead of another weapon. 

It was suggested in Discord and Indigo requested the suggestion be posted here for tracking. Please let me know if there's any questions or clarification needed. 

I can be contacted on Discord @Pinupski#9999  <@!168832328825569280>

**Comment by Darwe-Canine** [comment]
Believe this can be closed, as the builder now supports the Default IW enhancement feature.
