### ISSUE TITLE
JP Damage Change

### ISSUE THREAD

**Issue by Darwe-Canine** [lyrgard/ffbeEquip#199]
https://www.reddit.com/r/FFBraveExvius/comments/9a7grr/jp_new_damage_formula_uncovered/

Reddit has figured out the new JP damage formula.

**Comment by tomurderthelight** [comment]
this was in the comments. 

"it would be great if you'd make a checkbox for the new formula to (not) be used." 

lyrgard was tagged in the comment, but i wanted to copy it to here for visibility, and so that it didn't get lost.

**Comment by Indigo744** [comment]
Added in latest commits: https://github.com/lyrgard/ffbeEquip/commits/master
