### ISSUE TITLE
Viktor Build

### ISSUE THREAD

**Issue by Adezandee** [lyrgard/ffbeEquip#200]
Hi @lyrgard 
I've noticed a bug in build vs in-game stats for Viktor 7*:
- here is the build http://ffbeEquip.com/builder.html?server=GL#71638d60-a8a5-11e8-9a54-c928a3c07b3c
- here is in-game result
![screenshot_20180825-222850](https://user-images.githubusercontent.com/4415204/44622322-872a2300-a8b6-11e8-8003-bec55ee011d3.png)

There is a noticeable difference in DEF stat: 1221 (build) vs 1043 (IG)

Thanks

**Comment by Indigo744** [comment]
Fixed in latest commits: https://github.com/lyrgard/ffbeEquip/commits/master

**Comment by lyrgard** [comment]
@Adezandee you have a +100% DEF buff in your link. It can explain the difference.

**Comment by Adezandee** [comment]
@lyrgard oh sorry ! didn't see that my bad. You're right
