### ISSUE TITLE
Propose a Dark mode

### ISSUE THREAD

**Issue by Indigo744** [lyrgard/ffbeEquip#206]
Some users would love to see a proper dark mode implemented directly in FFBEEquip.

Plugins that turns page into darker page doesn't fare well with the site.

It could be a user's settings (a toggle somewhere?) that the user can set.
It should be stored in user's settings.

This thread aims to discuss on what needs to be made dark(er).

**Comment by Indigo744** [comment]
Question: where should the dark/light toggle be situated?

**Comment by lyrgard** [comment]
I think we should have a "user account setting" button somewhere. Probably
near the log out button, when logged in

**Comment by Indigo744** [comment]
WIP: 
![image](https://user-images.githubusercontent.com/7137528/44781369-76163600-ab84-11e8-887d-6d49217a4afb.png)

**Comment by lyrgard** [comment]
Looks really nice !

**Comment by Indigo744** [comment]
@lyrgard The main issue I can see is actually applying the dark theme.

Doing this in JS leads to seeing first the default version, then the dark version (i.e. like a "flash").
And I even try to perform the style injection directly in the head with a basic script. It's going to be much worse when using user's settings (i.e. have to wait for everything to load from user).

The best thing would be to switch dark/light theme from server side switch. However, we can't because there is no server side information on users.

The only solution I can think of is something along the way reddit handle dark mode: with a subdomain (e.g. https://dm.reddit.com/r/FFBraveExvius).

Hence, server side, we could decide which style to give according to the subdomain or not.

Is it something possible? What do you think?

**Comment by tomurderthelight** [comment]
wip theme looks nice, though still too bright for my taste.

the subdomain idea is intriguing. if i understand it correctly, it could make managing css files easier, at least.

**Comment by Darwe-Canine** [comment]
Dark Mode arrived, huzzah! Can close this one.
