### ISSUE TITLE
Tetra Sylphid's 3* MAG stat is incorrectly displayed

### ISSUE THREAD

**Issue by Indigo744** [lyrgard/ffbeEquip#212]
As reported by Discord user Coolie.

> It appears Tetra Sylphid's 3* MAG stat is incorrectly displayed.
> http://ffbeequip.com/espers.html?server=GL&o#eyJUZXRyYSBTeWxwaGlkIjp7Im5hbWUiOiJUZXRyYSBTeWxwaGlkIiwicmFyaXR5IjozLCJsZXZlbCI6MjAsInNlbGVjdGVkU2tpbGxzIjpbIjFfMCIsIjJfMSIsIjJfMiIsIjJfMyIsIjNfMyIsIjNfMiIsIjNfMSIsIjNfMCIsIjRfMSIsIjRfMCIsIjNfbTEiLCIyX20yIiwiMV8xIiwiMV8yIiwiMF8yIiwiMV8zIl19fQ==
> This shows 6960 MAG, in-game it shows 7000 MAG on the same build

**Comment by Darwe-Canine** [comment]
Believe this can be closed, esper stat scaling has been corrected and currently all of my builds match in-game values. Should open a new issue if another problem is discovered.
