### ISSUE TITLE
Unit Search: image not found for 5 units

### ISSUE THREAD

**Issue by Indigo744** [lyrgard/ffbeEquip#217]
When the following units appear, they don't have any image and an error is logged in the console stating the image couldn't be found:

unit_icon_100000102.png     **Rain**
unit_icon_100000202.png     **Lasswell**
unit_icon_100001101.png     **Tronn**
unit_icon_100000901.png     **Rizer**
unit_icon_100001001.png     **Leah**

**Comment by lyrgard** [comment]
I added them.
