### ISSUE TITLE
localStorage: fix bug and rework

### ISSUE THREAD

**Issue by Indigo744** [lyrgard/ffbeEquip#219]
Issue that actually happened to Kujo (discord): in unit search, searching for a unit (e.g. Marie) bring nothing in result. After clearing whole cache, it works again.

This behavior can be reproduce by using Dev tools, going to localStorage, and setting `GL/unitSearch.json` too an empty array `[]` for instance. This wont trigger any refresh from server.

Additional investigation may be needed to determine how an empty array (or incomplete array) could be saved to the localStorage.

**Comment by Indigo744** [comment]
Also, check for failsafe / error handling when localStorage is full (`QuotaExceeded` exception and such)

**Comment by Indigo744** [comment]
Also, search for a compression algorithm to be able to store more data.

Relevant article on quota limit for browsers: https://www.html5rocks.com/en/tutorials/offline/quota-research/

**Comment by lyrgard** [comment]
I'll work on it at lunch, I think it is urgent as users are impacted in production

**Comment by Indigo744** [comment]
A localStorage wrapper, with timeout: https://github.com/pamelafox/lscache
A compression based on LZW and made for JS string: http://pieroxy.net/blog/pages/lz-string/index.html

**Comment by lyrgard** [comment]
Compression added, using lz-string
