### ISSUE TITLE
esper planning, from discord

### ISSUE THREAD

**Issue by tomurderthelight** [lyrgard/ffbeEquip#223]
AmphisToday at 10:48 AM
Suggestion for FFBEEquip - The ability to plan out your espers and save the builds. Currently I'm putting the Lv60 points into the espers to plan where to go, but when I build a unit, it takes all the abilities into consideration, even if the esper is not at that level. Granted I could just save a link to a build but would be nice to have a plan to work to as well as keeping an accurate representation of what the current epser build is

**Comment by Indigo744** [comment]
Duplicate of #224 
@tomurderthelight can you close it?
