### ISSUE TITLE
Unit skills are only for the last added unit

### ISSUE THREAD

**Issue by mkujawa** [lyrgard/ffbeEquip#234]
STR:
  1) Open the builder 
  2) Choose a unit, like Orlandeau
  3) Click the + to add another unit to the party
  4) Choose the new unit, different from the unit in step 2, like Raegen
  5) Switch back to Orlandeau's tab
  6) Click the goal dropdown

The skills in the goal dropdown will be for Raegen, not Orlandeau.

This issue can result in an exception:
  1) open the builder
  2) choose Orlandeau
  3) Set Divine Ruination +2 as the goal
  4) Click the + to add another unit to the party
  5) Choose a new unit, different from step 2, like Raegen
  6) Switch back to Orlandeau's tab
  7) Attempt to clear the custom goal by pressing the X button

Because Divine Ruination +2 is no longer in the skill list, this results in `getSkillFromName` returning `undefined`, which gets passed to `formulaFromSkill`

**Comment by lyrgard** [comment]
It has been solved.
