### ISSUE TITLE
Exclusion window overlaps with itself after clearing

### ISSUE THREAD

**Issue by juances19** [lyrgard/ffbeEquip#235]
Steps to reproduce:

Exclude a bunch of items
https://i.imgur.com/MOC70pb.png

Click "Reset item exclusion list"
https://i.imgur.com/omzyahh.png

You can do it multiple times, every time you press the rest button it opens a new window, and you'll have to close every single one of them to go back. Every time you do it the background gets darker and darker until it's a black hole 
https://i.imgur.com/fsMlras.png

**Comment by lyrgard** [comment]
It is solved.
