### ISSUE TITLE
Overlapping overlay on mobile

### ISSUE THREAD

**Issue by Darwe-Canine** [lyrgard/ffbeEquip#240]
Found by Kriss Heitala on Discord.

On Chrome for Android (at least) "Export as CSV" on the Inventory page, and "Share Unit Collection" on the Units page overlap the drop-down page selector.

![screenshot_2018-09-17-20-13-41-274_com microsoft emmx](https://user-images.githubusercontent.com/42034289/45642610-b5022200-ba86-11e8-911f-97259ba1ac86.png)

![screenshot_20180917-143157](https://user-images.githubusercontent.com/42034289/45642665-debb4900-ba86-11e8-912f-70f97147d30d.png)

**Comment by lyrgard** [comment]
Done ;-)

**Comment by Indigo744** [comment]
I don't think the issue is fully closed : 
![image](https://user-images.githubusercontent.com/7137528/45671425-afa7e480-bb25-11e8-9e7b-3072b2ffaea2.png)

I understand what is the issue. Wait for my PR 😺
