### ISSUE TITLE
Possible Jump Damage Cap

### ISSUE THREAD

**Issue by Darwe-Canine** [lyrgard/ffbeEquip#248]
FFBE streamer Howl seems to have identified a jump damage cap of 300%, from training dummy testing with Reberta 7*. I'm still looking for more info and test results, not 100% sure if this is a general issue or just an issue with the new timed jump.

**Comment by lyrgard** [comment]
No able to reproduce now. It has been tested here : https://www.reddit.com/r/FFBraveExvius/comments/9iaa54/psa_reberta_is_an_insanely_strong_finisher_now/?st=jmg7n74b&sh=b8032ed2 and confirmed to go higher than 300%

I'll close the issue for the time being, but stay alert regarding this point.
