### ISSUE TITLE
How to get the data source?

### ISSUE THREAD

**Issue by mgsers** [lyrgard/ffbeEquip#256]
Hey! I am curious about how to get the data source. Unpack ? I want to collect some data by myself. Thank you!

**Comment by lyrgard** [comment]
I don't extract the data myself, I take it from here :
https://github.com/aenigmatic/ffbe

**Comment by mgsers** [comment]
@lyrgard Thanks! But i can't find the image, icon, etc? Only the json files.

**Comment by Indigo744** [comment]
@mgsers May I suggest you to have a look at the [Wiki page on data mining](https://exvius.gamepedia.com/How_to_data_mine) (especially the "Extracting assets from cache files" paragraph).

**Comment by mgsers** [comment]
@Indigo744  Got it! Thanks!
