### ISSUE TITLE
DEF being calculated wrong for Demon Rain.

### ISSUE THREAD

**Issue by seilaoque** [lyrgard/ffbeEquip#27]
I've fixed 3 Patriotic Recalls for demon rain and asked for a build for "Physical Damage" and the builder returned DEF of 587 when the correct amount should be close to 400.

maybe something with the doublehand logic might be affecting stats other than ATK?

**Comment by lyrgard** [comment]
@seilaoque : you're right, DH bonus to the desired stats was also applied to the others stats. This should now be corrected. Can you confirm ?

Thanks a lot for reporting.

**Comment by seilaoque** [comment]
yes, it seems correct now.
