### ISSUE TITLE
Lucius calculation missing passive attack stat

### ISSUE THREAD

**Issue by DefiantGlobe** [lyrgard/ffbeEquip#272]
At 5★ Level 1, Lucius has a trait called "Demonic Brawl" that : 
"Enables dual wielding of one-handed weapons
 Increase ATK (50%) when equipped with a fist
 Increase ATK (200%) when unarmed"
The calculator does not include the 200% ATK boost when unarmed.

**Comment by lyrgard** [comment]
It has been corrected ! Thanks for reporting
