### ISSUE TITLE
attack element doesn't seem to work

### ISSUE THREAD

**Issue by seilaoque** [lyrgard/ffbeEquip#28]
If I choose Light as my element and ask the system to build Orlandeau for physical damage, it still suggests that I run Dandelga...

**Comment by lyrgard** [comment]
Attack element is not a way to choose a specific element for the builder to use. It is just a way to tell the builder: "I'm going to use a skill that has a innate element". This element will be added to the elements of the weapons when computing the build, to calculate the damage. It is to work with skill with innate element like Fohlen's or Fryevia's skill.

However, your clearly not the first to tell me that, so I'll make it more clear.

**Comment by lyrgard** [comment]
I renamed the field "Skill innate element(s)"
