### ISSUE TITLE
Unreleased items in inventory

### ISSUE THREAD

**Issue by Darwe-Canine** [lyrgard/ffbeEquip#285]
If a user adds an unreleased item to their inventory (by creating a 7* character that isn't currently available in the GL version (this is a separate bug)) then adding their STMR through the unit page, there is no way to remove that STMR from the user's inventory. The builder will build with it when set to "use own equipment", and will correctly mark it with a green 1 when set to "use all equipment" with "exclude unreleased items" unchecked, but it does not display in the inventory, so there is no way to remove it. Unreleased items should either be maxed at 0, or shown in the inventory if they are owned.

**Comment by lyrgard** [comment]
Corrected : 
- not anymore possible to awaken to 7\* a unit whse 7\* is not yet released
- "not yet released" items somehow added to inventory will be displayed in the inventory
