### ISSUE TITLE
GL 7* support for new awakenings

### ISSUE THREAD

**Issue by Cerberus-Malthael** [lyrgard/ffbeEquip#301]
New 7* GL Awakenings:

- Yuna
- Lotus Mage Fina
- Lulu
- Aranea
- Prompto
- Basch
- Duke
- Kunshira

Source: https://dm.reddit.com/r/FFBraveExvius/comments/a5fg6o/gl_new_7_awakening_banners_7_release_special_part/

**Comment by lyrgard** [comment]
Done
