### ISSUE TITLE
E_LIGHTNING does not work as a conditional effect.

### ISSUE THREAD

**Issue by Morphuesss** [lyrgard/ffbeEquip#302]
When using E_LIGHTNING as a conditional effect, the error appears.

"ffbeequip.com says
Error at position 4. E_LIGHTNING is not a valid variable"
![e_lightning](https://user-images.githubusercontent.com/45901392/50045504-b1684200-0059-11e9-860b-a38f2f2ea08c.png)

I have tested all of the elemental effects and they all work properly,

**Comment by lyrgard** [comment]
It is E_THUNDER ;-)

Le sam. 15 déc. 2018 à 18:09, Morphuesss <notifications@github.com> a
écrit :

**Comment by Morphuesss** [comment]
Ah thank you lyrgard!  You have amazing work here by the way.  The help document for conditional effects says E_LIGHTNING and not E_THUNDER so I guess that is were I fell astray.
![e_lightning](https://user-images.githubusercontent.com/45901392/50046006-f8f2cc00-0061-11e9-8922-d38ecc192d36.png)
