### ISSUE TITLE
Equipment Equip With Materia Not Calculated

### ISSUE THREAD

**Issue by Jerethkhan** [lyrgard/ffbeEquip#308]
Not sure if this is an oversight, bug, or intended. Equipment that a character can't equip by default but could if they equip "Use" materia is not factored in.
For example, Tilith cannot equip weapons. I have a "Use Grappling Weapons" and built a weapon in the Steel Castle to have +29% MP. With all of that info in FFBE Equip, the system never checks to see if that's a viable option.

**Comment by lyrgard** [comment]
Trying all combinations with "Use ..." materia adds complexity to the calculations, slowing them down. So by default, the builder doesn't consider it.

But you can ask it to consider it by checking the 'Try "Allow use of <type>" items' options ;-)
