### ISSUE TITLE
Liquid Metal Slime has ability slots

### ISSUE THREAD

**Issue by wrjones104** [lyrgard/ffbeEquip#312]
I was just updating my parameter mission builds and I saw that the builder is allowing abilities on Liquid Metal Slime. He should just have accessory slots and that's it, I believe!

Thanks as always for the amazing work!

**Comment by Darwe-Canine** [comment]
Looks like this one has been fixed, as I'm not seeing it anymore, so I'll close it. Please let us know if it reoccurs, as it could be related to opening new unit tabs when existing tabs are open.
