### ISSUE TITLE
Minor spelling/grammar errors (ENG)

### ISSUE THREAD

**Issue by Sh1nma** [lyrgard/ffbeEquip#319]
Issue:  [](https://ffbeequip.com/encyclopedia.html)
release is should be released.
element: <label>Show not release yet items</label>

Expected should be 'Show items not yet released', or 'show unreleased items'.

Issue: [](https://ffbeequip.com/builder.html)
Equipment is the same singular and plural (no equipments)
Element: <label>Exclude not released yet equipments</label>
Expected should be Exclude unreleased equipment. or Exclude unreleased equipment.

Exclude not released yet equipments

**Comment by lyrgard** [comment]
Thanks a LOT for reporting it. It really help.

It's corrected now, using your wording suggestion.
