### ISSUE TITLE
Aurora Fryevia still flagged as time-limited unit

### ISSUE THREAD

**Issue by stuaroo** [lyrgard/ffbeEquip#320]
The [Myra/A. Fry announcement](https://lapis-prod-staticnews-gumi-sg.akamaized.net/prod//en/img/FanFestaMyraGachaSummonv2.jpg) mentions that both will be added to the UoC pool after the banner ends, but Aurora Fryevia is still flagged as a time-limited unit under My units tab, as well as in the unit counts on the left sidebar.  

If I followed the code correctly, I believe updating A.Fry's type from `event` to `summon` on [static/GL/releasedUnits.json](https://github.com/lyrgard/ffbeEquip/blob/master/static/GL/releasedUnits.json) will fix the unit counts, but I'm unsure if that's the only flag for time-limitedness (which is why I'm submitting as an issue rather than a pull request!)

**Comment by lyrgard** [comment]
Thanks a lot for reporting it.

Your analysis was exactly spot on, I just needed to correct releasedUnits.json to change that. It's done !
