### ISSUE TITLE
Dual Black Magic issues with Trance Terra and Barbariccia

### ISSUE THREAD

**Issue by Darwe-Canine** [lyrgard/ffbeEquip#323]
Trance Terra's Dual Black Magic is only allowing two white magic spells to be selected. It appears that both TT's DBM and Dual White Magic are both referencing skill 200160; DWM should reference 219500, but that skill has an incorrect effect and effect_raw in the data export.

Barbariccia's DBM is functioning as Triple Black Magic.

**Comment by Bdazzle** [comment]
Barbaraccia's Triple Black should reference skill 228042. TT's Dual White should reference 213980, which looks like the correct version (other unit's with Dual White reference that number) and has the correct effect.
