### ISSUE TITLE
Shadow Dragon Scale

### ISSUE THREAD

**Issue by dogeregod** [lyrgard/ffbeEquip#349]
Shadow Dragon Scale from the event The Man in Black (old FF IV KM event) and Dwarven Castle (latest FF IV KM event) does not stack together in the inventory list, the rarity is different, the one is 7* and the other is 8* instead

Check this images
[image 1](https://imgur.com/ZFn5brB)
[image 2](https://imgur.com/a6LCkxi)

**Comment by tomurderthelight** [comment]
i asked about it in the reddit discord. copy/paste.

11:10 AM
tmtl
does anyone here happen to have both of the shadow dragon scales from the ff4 events? could use a screen shot of if they are the same or different rarity.

11:10 AM
norby89
they use the same slot ingame

11:10 AM
tmtl
that's what i expected. there's two different entries in the data, though.

11:11 AM
norby89
maybe it changed after it was datamined
