### ISSUE TITLE
New damage formula applied incorrectly to some attack type/damage type combinations

### ISSUE THREAD

**Issue by Saiba15** [lyrgard/ffbeEquip#402]
It is currently applied to p_damage_mag and p_damage_spr (and their derivatives), when it shouldn't because those are phys type **magic** damage, and isn't applied to skills like Reberta's breaths, which are mag type **phys** damage. (On that point, could we have a m_damage_atk custom goal ? And h_damage_multicast too while I remember about it)

**Comment by Darwe-Canine** [comment]
This appears to have been corrected and can be closed (although we could still use h_damage_multicast as a custom goal, I can open a separate issue for that).
