### ISSUE TITLE
Lucius's Demon Chemistry enhancement using wrong labels on the builder

### ISSUE THREAD

**Issue by stuaroo** [lyrgard/ffbeEquip#410]
The default Demon Chemistry is a passive with phys/mag counters and no stat increases.  Enhancing it to +1/+2 adds 25%/50% ATK respectively.  The label for this on the builder currently defaults to Demon Chemistry +1 with no option for +2.  However, selecting Demon Chemistry +1 does appear to apply the maximum 50% ATK increase.  To help explain a little better, here is a table with ATK increases and the names used on the wiki and the builder respectively:

ATK increase % | Wiki name | Builder name
:---:|:---:|:---:
None | Demon Chemistry | Demon Chemistry not unlocked
25% | Demon Chemistry +1 | Demon Chemistry
50% | Demon Chemistry +2 | Demon Chemistry +1

Looking up Demon Chemistry under `GL/unitsWithPassives.json`, the first array under `levels` is empty.  I'm guessing that is currently a flag for an unlockable/latent ability, as looking up an actual latent ability, Crimson Destiny, in the same list also shows an empty array as the first element:

```
"enhancements": [
	{"name":"Demon Chemistry","levels":[[],[{"atk%":25}],[{"atk%":50}]]}
	...
	{"name":"Crimson Destiny","levels":[[],[{"atk%":10,"hp%":10,"killers":[{"name":"human","physical":25}]}],...
```

I can also confirm the same issue on another enhancement where the base ability has no stat increases: Elfreeda's Ice Prism.  This displays in the builder as: Ice Prism not unlocked, Ice Prism, and Ice Prism +1.

**Comment by lyrgard** [comment]
It has been corrected. Thanks for reporting it.
