### ISSUE TITLE
Physalis Build Bug

### ISSUE THREAD

**Issue by Darwe-Canine** [lyrgard/ffbeEquip#414]
Using the attached inventory (rename it from .txt to .json), build Physalis for physical damage with her TMR pinned, you'll get [a build with two guns and one missing materia](https://ffbeequip.com/builder.html?server=GL#db913430-178f-11ea-9f71-fbb311f0fb55). Pinning Awesome Swordsman or Dual Wield as well doesn't change the build results, but pinning AS and replacing Arcturus with Rising Sun (FFBE) results in [a higher damage build](https://ffbeequip.com/builder.html?server=GL#f84fe850-178f-11ea-9f71-fbb311f0fb55). You can also get the second (superior) build by banning Arcturus. The first build does have higher %atk, but lower atk and lower damage.

Raw data for Physalis's DW ability shows it as [0, 3, 14, [14]], which I think is correct? Unless aEnigma updated his data more than once.

[FFBE_Equip_-_Equipment_1.txt](https://github.com/lyrgard/ffbeEquip/files/3928903/FFBE_Equip_-_Equipment_1.txt)

**Comment by Darwe-Canine** [comment]
Second Physalis bug, Triple Strongest Attack in the drop-down is only acting as W-Cast, not T-Cast.

Third Physalis bug, using All Equipment, No STMR, Exclude Unreleased Equipment:

If you force Wind, you get [a build with Whirlwind and Quicksilver](https://ffbeEquip.com/builder.html?server=GL#63941a90-17c8-11ea-9f71-fbb311f0fb55). If you imperil Wind by 100+ (whether or not you also force Wind), you get [a build with Quicksilver and Zwill Crossblade](https://ffbeEquip.com/builder.html?server=GL#8d8f2c90-17c8-11ea-9f71-fbb311f0fb55) that does less damage. I don't know if this is related to either of the other two issues.

**Comment by lyrgard** [comment]
So, can be closed now ?
