### ISSUE TITLE
Anima 3* still missing on FFBE-Equip

### ISSUE THREAD

**Issue by UltimateChaos2000** [lyrgard/ffbeEquip#425]
As the topic said: The esper Anima is still missing in her 3star form to modify on FFBE-Equip.
Same for Bahamut 2* (but its just released a few days ago, so its not a real issue)

Regardful, Chaos.

**Comment by lyrgard** [comment]
Anima 3* is available in FFBE Equip since a long time ago, as is Bahamuth, since Friday.

you problably need to clear your local storage for ffbeequip.com in order to download the updated data.

**Comment by UltimateChaos2000** [comment]
thanks for your fast answer.

I have now cleared all my browser data (chookies, visted sites, cache, etc.). i still dont see the updates of these two espers. 

I tried to use ffbe-equip on my smartphone - there the espers are here, as you said.

can you probably tell me where the browser saves the data from ffbe-equip?
i am using win7, browser Opera

**Comment by lyrgard** [comment]
I'm not familiar with Opera, so I can't tell you how to do it, but what you
need to clear is named "local storage", for ffbeequip.com. It's not
cookies, cache or visited site, it's yet another thing, local storage.

**Comment by UltimateChaos2000** [comment]
I have resetted my browser completly. Now it works.

Thanks for your time.
