### ISSUE TITLE
Esper Build Link errors

### ISSUE THREAD

**Issue by Darwe-Canine** [lyrgard/ffbeEquip#435]
Esper build links improperly generate for any esper with nodes 54 and higher selected, seemingly in the generation of the Hex value for the link. Filling a 3* esper's grid fully causes only node 4 to be populated.

**Comment by Darwe-Canine** [comment]
From tmtl/erim:

hm. this error just gets strange.
with odin 3*, you can select all but node 39 without selecting anything on the top and bottom rows. that link shares fine - https://ffbeequip.com/espers.html?server=GL&o#Odin%7C3%7C60%7Cfffffffffdffe000
the next chain of nodes is 54 -> 53 -> 52.
select 54, and it's removed in the shared link.
select 54 and 53, and they are removed in the shared link, but 52 is added.
select all three, and the entire outer layer is removed, except for nodes 38 and 39. note that node 39 was not selected, as it's access comes from the top row.

**Comment by kaldios** [comment]
everything selected except for nodes 52 and 53 generates https://ffbeEquip.com/espers.html?server=GL&o#Odin|3|60|ffffffffffffe800
from the earlier link, this adds nodes 39 and 53, which can't be selected on their own. everything else on the top and bottom row is unselected.
everything selected except for node 52 has the same result as selecting only nodes 53 and 54 in the top and bottom rows.
i added all of the nodes on the bottom row one at a time, and they were just removed.

back to the first link-
selecting nodes 54 and 55, the link removes them and adds 53.

**Comment by Darwe-Canine** [comment]
From tmtl/erim
https://stackoverflow.com/questions/40608111/why-is-18446744073709551615-1-true
interesting.
https://stackoverflow.com/questions/48981762/mysql-bigint-max-value-stored-in-javascript-variable
there's the problem.
"That value cannot be represented accurately in a JavaScript number. You can store it as a string, though that's probably not very useful."
"Part of the 64 bits are used as an exponent. For exact integer values you only have the range of ±2^53-1. "

**Comment by theultramage** [comment]
"JavaScript numbers are always 64-bit floating point."
Trying to convert the whole thing into an integer was a mistake. Particularly if there were more than 64 panels, it would have never worked. You need to review both hex2bin() and bin2hex() as both rely on this method of conversion. I suggest checking if there is no built-in (or a simple code snippet) that can do the job correctly on arbitrarily long strings.
