### ISSUE TITLE
0-turn duration skills

### ISSUE THREAD

**Issue by Darwe-Canine** [lyrgard/ffbeEquip#462]
from u/Hyperion
Hi Lyrgard. On the unit pages you have 0-turn skills as 'for this fight' rather than 'for this turn'. Example below of Freya (VP)

![image](https://user-images.githubusercontent.com/42034289/82325510-5bfc3700-99a9-11ea-8545-3fce0bdeca39.png)

![image](https://user-images.githubusercontent.com/42034289/82325527-63234500-99a9-11ea-9b49-72ab73d4e65d.png)

**Comment by kaldios** [comment]
not lyrgard's fault.

**Comment by kaldios** [comment]
https://ffbeequip.com/unitSearch.html#eyJzZWFyY2hUZXh0IjoiXCJhZXJpYWwgYnVyc3RcIiIsImZ1bGx5RGlzcGxheWVkVW5pdHMiOltdfQ==
this should be fixed now.
