### ISSUE TITLE
Global: Error importing items

### ISSUE THREAD

**Issue by mluizvitor** [lyrgard/ffbeEquip#527]
I face errors when I try to import my item colection. It is the same error from a week ago and I don't have the new recipes/weapons from the events of this week. Thanks for your time.

![image](https://user-images.githubusercontent.com/57257682/120841798-58026f00-c542-11eb-99ff-f84a6a250cb9.png)

![image](https://user-images.githubusercontent.com/57257682/120841886-6d779900-c542-11eb-83db-03fa6b9524fa.png)

![image](https://user-images.githubusercontent.com/57257682/120841917-76686a80-c542-11eb-8379-06c8922d0a0b.png)

![image](https://user-images.githubusercontent.com/57257682/120841945-7e280f00-c542-11eb-945b-5bfa1ee7e550.png)

![image](https://user-images.githubusercontent.com/57257682/120842001-8e3fee80-c542-11eb-8fa1-ba184133b81a.png)

![image](https://user-images.githubusercontent.com/57257682/120842042-95ff9300-c542-11eb-9128-d5bc288fb35a.png)

**Comment by quintaur** [comment]
Same here, the last unit update in FFBEQ are rain&fina and lasswel&raegen back in January. I don't think it is being updated any longer :-(

**Comment by mluizvitor** [comment]
The last update solved this issue. I imported the same inventory colection file from four days ago and FFBE Equip does not shows any errors.

Example of previously missing equip:
![image](https://user-images.githubusercontent.com/57257682/121259882-00883a00-c887-11eb-8042-ef1230bee7d4.png)
