### ISSUE TITLE
lost wikiEntry's

### ISSUE THREAD

**Issue by tomurderthelight** [lyrgard/ffbeEquip#80]
`{"id":"315021700", "name":"Hawkeye", "wikiEntry":"Hawkeye_(Item)", "type":"throwing", "atk":36, "mag":42, "killers":[{"name":"bird","physical":50}], "access":["chest"], "icon":"item_11305.png", "sortId":657},`

`{"id":"1500000003", "name":"Seal of Destruction", "wikiEntry":"Tablet_of_Ruin", "type":"materia", "atk%":20, "lbFillRate":100, "exclusiveUnits":["302000605"], "access":["event"], "maxNumber":2, "icon":"ability_77.png", "sortId":90003},`

**Comment by lyrgard** [comment]
Done ! Thanks
