### ISSUE TITLE
goals/custom goals doc clarity.

### ISSUE THREAD

**Issue by tomurderthelight** [lyrgard/ffbeEquip#86]
i'll try to work on this. if you can think of anything else, or have suggestions, let me know.

* clearer usage explanation.
* examples of invalid goals.
* examples using skill multipliers for damage.
* explanation of calculating damage using debuffs/breaks.

notes:
ability modifier, you can use a custom formula, like '5.2 * P_DAMAGE' for a 5.2x ability
break %, you can adjust the monster DEF/SPR to reflect that

**Comment by lyrgard** [comment]
For the ability modified, perhaps a reminder that "ignore X% ennemy def" is just a multiplier to the base coef, and that they should use the final calculated coef ?

I often have question because people don't understand that the first term of the formula is different than the others. I always visualized an image showing a formula, with the first term in red and the others in another color, with arrows explaining the role of each.

Concerning debuff/break, it is not related to custom formula, so it may not be the best place to put that, what do you think ?

If you think of a better presentation that just a single page, I can change the code to display it another way. Perhaps let the custom formula popup clean (or just the list of available terms) and a link to an help page ?

**Comment by tomurderthelight** [comment]
for ability modifier, that is a good reminder to include. that makes divine ruination a better example now that i look at it again. it will cover both ignore def and skill damage multiplier.

i was thinking of doing multiple examples for explaining how the first differs from the rest. start with an example that uses only one goal, then expand into building for multiple goals from there.

debuffs and breaks, since they are not part of the goal formula, would be an explanation of using the target monster section as intended.

this has potential to become it's own page or section. it might also change the 'how to use' section seen when first visiting the page. let's leave that decision for later, as we work out details and explanations.

**Comment by lyrgard** [comment]
Thanks a lot. I took it, changed it a little and integrated it to the builder page !

**Comment by tomurderthelight** [comment]
you added quite a bit, too. very nice!
it needs a few minor touch ups, though.

"use Fryevia's Frost " Flower Blitz. - not sure why it's missing the last couple of words.

"Fill (in) information on the monster"

fix "exlude"/exclude typo.

change
To allow this tool to suggest you TMR to farm
to
To allow this tool to suggest TMR for you to farm

:)

possibly, also add notes under "Equipment selection" in regards to how "specifically excluded items" works?

**Comment by tomurderthelight** [comment]
i'm still working on this, but drawing blanks at the moment, so i thought i'd share it and see what you think. using brackets for emphasis points. the examples are meant to be quick notes to give a more visual idea of what's written. i need to add in some invalid examples to go with them. the warning at the end of the first paragraph could probably be written better/clearer as well.

the page breaks down into three parts, of which experienced users really only need to see one of them. how difficult would it be to make each section (how to, sample/common formulas, and variables) collapsible? if logged out, all are expanded, and if logged in, only variables is expanded.

...

How to use this:

Custom goals are used to define how you want to build your unit. Each custom goal contains one or more [EXPRESSIONS], separated by semicolons [;], without a semicolon at the end. Custom goals can be as simple as a single [EXPRESSION] using a single [VARIABLE], as complex as dealing damage while self-sustaining mp, or even as complex as to be immune to death, elements, and status ailments, while being self-sustaining. Be forewarned, however, that the more variables that are included in a custom goal, the more time it will take to calculate the build, or the higher the risk you run of freezing up your device. Reducing the number of cores in use can help prevent freezes, but increases the time needed to calculate the build. 

The [first EXPRESSION] provides the builder with it's overall goal; what to maximize, while meeting any following conditions. This [EXPRESSION] is how the builder decides that one build is better than another.
The [first EXPRESSION] may contain one or more [variables], using multiplication [*], division [/], or addition [+] to create a single overall value. However, it may not contain the comparison operator [>], which will cause an error.
Examples: {HP}, {HP * DEF}, {5.2 * P_DAMAGE}.

Each [EXPRESSION] after the first is a [CONDITION] or a [SHORTCUT] for a condition. 
Each [CONDITION] must compare one or more [VARIABLES] to a specific value; [VARIABLE > VALUE]. The left side of the [CONDITION] works the same as the [first EXPRESSION]. The [>] operates as [>=], making the [VALUE] provided the minimum goal to satisfy the condition. The right side of the [CONDITION] must be a number.
[SHORTCUTS] contain one or more sets [CONDITIONS] with fixed [VARIABLE > VALUE] pairs, and cannot be part of a [CONDITION]. For example, the [CONDITION] {R_CONFUSION > 100} is the same as the [SHORTCUT] {I_CONFUSION}.
Examples: {M_DAMAGE; HP > 6000}, {P_DAMAGE; MP * MP_REFRESH > 45}, {H_DAMAGE; I_PHYSICAL; R_FIRE > 200}

**Comment by lyrgard** [comment]
I like it a lot. It is clear and concise.

Just some remarks : I would rather use more precise definition for terms. For instance, EXPRESSION could be what the first TERM is, and then CONDITION is then defined as EXPRESSION > VALUE. You can then say that a custom goal is a suit of TERMS separated by semicolons, the first TERM needed to be an EXPRESSION, and the ones after CONDITIONS. What do you think ?

No problem to make collapsible sections. I also plan to have the VARIABLE clickable to add them to the formula without typing them. Same with the example formula, we could compile a list of often used formula, and add it to the text box by a simple click.

**Comment by tomurderthelight** [comment]
i like the idea. i don't know if 'term' fits, though. formula/formulae, maybe? i'll rework it when i can think straight. 

i was going to bring up the clickable variables and such, but figured it was already on the to do list since it was a great idea.

**Comment by tomurderthelight** [comment]
this is very rough, but it gives an idea of what i wanted to cover for using other sections of the builder with custom goals. a lot of this would probably work better as part of a larger general faq/how-to, but my poor brain doesn't want to go that way.

the bullet point is from the wiki's mechanics page for damage calculations. 

....

{Some restrictions apply to custom goals.} [collapsable within 1st section, always collapsed.]

custom goals are not able to force weapon elements or account for elemental resistances and weaknesses. nor are they able to automatically account for damage boosts like skill multipliers, buffs, debuffs, and def or spr ignore.

to account for a monster's strength or weakness to elements, and how it affects damage, you have to enter their elemental resistances into the monster section. some monster information is saved in the 'monster list', and while the monster section is not always visible, any information contained within is always considered when building a unit.

to force a weapon element, you have to tell the builder that the monster you are fighting is significantly weaker to that particular element than it is to any other. for example, if i wanted to build a gilgamesh carry unit, i would enter "-99" light resistance, and leave the rest at 0. note that this will throw off any damage calculations, since you are telling the builder that light weapons do more damage.

to account for skill multipliers, you have to multiply the damage variable by the skill multiplier. for example, to calculate damage using a physical attack with a 2.6 multiplier, you would use {2.6 * p_damage}.

to account for buffs, you need to enter the buff % into the unit's information, next to the relevant attribute. for instance, if i wanted to calculate noctis' physical damage with a 100% atk buff, his unit information would read as [atk : 158 : +30 : 100%].

to account for def/spr breaks and ignores, you have to change the relevant enemy attribute value. {this has to be calculated outside of the builder, then entered. it will not do it for you.} 

* {Enemy DEF/SPR is calculated after a debuff and ignore defense skill - Enemy Base DEF/SPR * (100% - Break %) * (100% - Ignore Defense/Spirit %)}

example, 45% break of 150 def: 100 - 45 = 55. 150 * .55 = 82.5. round up and enter 83.
example, 25% ignore of 175 def: 100 - 25 = 75. 175 * .75 = 131.25. enter 132.
example, 65% break and 25% ignore of 125 def: 125 * .35 * .75 = 32.8. enter 33.

**Comment by lyrgard** [comment]
Nice !

Just as a note, I added E_FIRE, E_ICE, and so on to allow to specify a required element for the build. They are special condition that need to be alone, without > and value.

when one or more of those are in the custom formula, the build is required to have ALL those elements and NONE other.

**Comment by tomurderthelight** [comment]
i will update my scribbles to remove the 'force element' section. did you include a variable for 'no element'? and what happens if someone tries to force more elements than are equipable?

**Comment by tomurderthelight** [comment]
better, but it still doesn't feel 'done'. thoughts?
...

How to use this:

Custom goals are used to define how you want to build your unit. Each custom goal contains one or more [formulae], separated by semicolons [;], without a semicolon at the end. Custom goals can be as simple as a single [EXPRESSION] using a single [VARIABLE], as complex as dealing damage while self-sustaining mp, or even as complex as to be immune to death, elements, and status ailments, while being self-sustaining. 
Be forewarned, however, that the more unique variables that are included in a custom goal, the more time it will take to calculate the build, or the higher the risk you run of freezing up your device. Reducing the number of cores in use can help prevent freezes, but increases the time needed to calculate the build. 
	
The first [formula] is an [EXPRESSION] that provides the builder with it's overall goal; what to maximize, while meeting any following conditions. This [EXPRESSION] is how the builder decides that one build is better than another.
[EXPRESSIONS] may contain one or more [variables], using multiplication [*], division [/], or addition [+] to create a single overall value. However, they may not contain the comparison operator [>], which will cause an error.
Valid examples: {HP}, {HP * DEF}, {2.6 * P_DAMAGE}.
Invalid examples: {HP;}, {HP * SPR > 1}

Each [FORMULA] after the first is a [CONDITION] or a [SHORTCUT] for a condition. 
Each [CONDITION] must compare an [expression] to a specific value; [expression > VALUE]. The [>] operates as [>=], making the [VALUE] provided the minimum goal to satisfy the condition. The right side of the [CONDITION] must be a number.
[SHORTCUTS] contain one or more sets [CONDITIONS] with fixed [expression > VALUE] pairs, and cannot be part of a [CONDITION]. For example, the [CONDITION] {R_CONFUSION > 100} is the same as the [SHORTCUT] {I_CONFUSION}.
Valid examples: {M_DAMAGE; HP > 6000}, {P_DAMAGE; MP * MP_REFRESH > 45}, {H_DAMAGE; I_PHYSICAL; R_FIRE > 200}
Invalid examples: {HP; SPR}, {MP; MAG > 1;}, {MP; M_DAMAGE > 1 + 1}, {DEF; DEF > SPR}, {SPR; R_THUNDER * I_FIRE > 1}

....

{Some restriction apply to custom goals.} [collapsable within 1st section, always collapsed.]

Custom Goals are not directly able to account for damage variances caused by:
* Unit skill multipliers
* Unit buffs and breaks
* Enemy def and spr, Buffs, Breaks, and Ignores
* Enemy Race/Killer Vulnerability
* Enemy elemental resistance
How do we help Custom Goals account for these variances? 

Unit Skill Multiplers: Skill Multipliers can be entered directly into the custom goal as a multiplier of the damage variable. For example, to calculate damage using a physical attack with a 2.6x multiplier, you would use {2.6 * p_damage}.
	
Unit Buffs and Breaks: Unit Buffs and Breaks are entered into the unit's information, in the third box next to the affected attribute. Buffs and Breaks stack additively, but only the strongest of each is applied. A 120% buff does not gain anything from applying a 50% buff, but does lose some potency to a 50% break, which results in a 70% buff. To calculate this combination of Buff and Break as part of Noctis' Atk, we enter this number (70%) next to his Atk attribute, so that his unit information reads as [atk : 158 (base) : +30 (pots) : 70% (buff)].
	
Choose your enemy: The builder does not know what kind of monster you are up against, so it defaults to a neutral enemy; 100 DEF, 100 SPR, no Race, and 0 elemental resistance. All of this can be changed to give you a better idea of how well your Units can deal with your chosen Enemy.
Note that some monster information is saved in the "Monster List", and while the Monster section is not always visible, any information contained within is always considered when building a unit. Once you have selected a monster from this list, it's information will be applied to the monster section. All you have to do is make changes to account for buffs, breaks, and imperils.

Enemy Def and SPR, Buffs, Breaks, and Ignores: Some monsters are harder to kill than others, some are vulnerable to breaks that others are immune to, and some bring their own Buffs to deal with. A Monster's DEF and SPR have to be calculated then entered, according to their default attribute, any Buffs they bring, and any Breaks you are going to apply. The builder cannot, currently, calculate this for you.

* {Enemy DEF/SPR is calculated after Buff, Break and Ignore skills: Enemy Base DEF/SPR * (100% + Buff % - Break %) * (100% - Ignore %)}
examples:
* 45% break of 150 def: 100 - 45 = 55. 150 * .55 = 82.5. round up and enter 83.
* 45% break and 80% buff of 50 def: 100 - 45 + 80 = 135. 50 * 1.35 = 67.5. enter 68.
* 25% ignore of 175 def: 100 - 25 = 75. 175 * .75 = 131.25. enter 132.
* 65% break and 25% ignore of 125 def: 125 * .35 * .75 = 32.8. enter 33.

Enemy Race/Killer vulnerability: Killers can be a huge help, but the builder has no idea which ones to use. Plant Killers aren't going to do any good against Bahamut. Click on each race that your enemy belongs to, and the builder will take any applicable killers into consideration.

Elemental Resistance: Elemental Resistance helps the builder choose the right weapon for the job. If the monster is not resistant or weak to any of them, then any weapon will do, but we don't want to go chasing after Ifrit with a Fire Axe. Like DEF and SPR, Elemental Resistance has to be calculated, then entered, but in this case it's all plus or minus with nice even numbers. To calculate elemental resistance, we take the base resistance, add the strongest buff the monster has for it, then subtract the strongest imperil we are planning to apply. For example, if the monster has 25% base fire resistance and a 50% fire resistance buff, and we have a 40% fire resistance imperil, the monster's calculated fire resistance will be 35%; 25 + 50 - 40.

**Comment by tomurderthelight** [comment]
tedious stuff. the first block is an attempt at clickable punctuation, but i left it spaced out so that escapes could be added. the idea is that if it's clickable, you don't need to find it with the keyboard. the rest is the variables that were listed when i copied the code from the file.


    <tr><td class="token">
    <a tabindex="-1" href="#" onclick="addToCustomFormula('
    *
    ')">
    *
    </a>
    &nbsp; &nbsp; &nbsp; 
    <a tabindex="-1" href="#" onclick="addToCustomFormula('
    +
    ')">
    +
    </a>
    &nbsp; &nbsp; &nbsp; 
    <a tabindex="-1" href="#" onclick="addToCustomFormula('
    /
    ')">
    /
    </a>
    &nbsp; &nbsp; &nbsp; 
    <a tabindex="-1" href="#" onclick="addToCustomFormula('
    >
    ')">
    >
    </a>
    &nbsp; &nbsp; &nbsp; 
    <a tabindex="-1" href="#" onclick="addToCustomFormula('
    ;
    ')">
    ;
    </a>
    </td><td>Easy access punctuation.</td></tr>

    <tbody>

    <tr><td class="token">
    <a tabindex="-1" href="#" onclick="addToCustomFormula('HP')">HP</a>, 
    <a tabindex="-1" href="#" onclick="addToCustomFormula('MP')">MP</a>, 
    <a tabindex="-1" href="#" onclick="addToCustomFormula('ATK')">ATK</a>, 
    <a tabindex="-1" href="#" onclick="addToCustomFormula('DEF')">DEF</a>, 
    <a tabindex="-1" href="#" onclick="addToCustomFormula('MAG')">MAG</a>, 
    <a tabindex="-1" href="#" onclick="addToCustomFormula('SPR')">SPR</a>
    </td><td>Value of the corresponding basic stat</td></tr>

    <tr><td class="token">
    <a tabindex="-1" href="#" onclick="addToCustomFormula('MP_REFRESH')">MP_REFRESH</a>
    </td><td>% of MP refresh per turn</td></tr>
    
    <tr><td class="token">
    <a tabindex="-1" href="#" onclick="addToCustomFormula('P_DAMAGE')">P_DAMAGE</a>
    </td><td>This is the total physical damage, taking into account the ATK, the elements, the killers, the damage variance, ...</td></tr>
    
    <tr><td class="token">
    <a tabindex="-1" href="#" onclick="addToCustomFormula('M_DAMAGE')">M_DAMAGE</a>
    </td><td>Same as P_DAMAGE but for magical damage</td></tr>
    
    <tr><td class="token">
    <a tabindex="-1" href="#" onclick="addToCustomFormula('H_DAMAGE')">H_DAMAGE</a>
    </td><td>Same as P_DAMAGE but for hybrid damage</td></tr>
    
    <tr><td class="token">
    <a tabindex="-1" href="#" onclick="addToCustomFormula('J_DAMAGE')">J_DAMAGE</a>
    </td><td>Same as P_DAMAGE but for jump damage</td></tr>
    
    <tr><td class="token">
    <a tabindex="-1" href="#" onclick="addToCustomFormula('S_DAMAGE')">S_DAMAGE</a>
    </td><td>Same as P_DAMAGE but for summon damage</td></tr>
    
    <tr><td class="token">
    <a tabindex="-1" href="#" onclick="addToCustomFormula('P_DAMAGE_MAG')">P_DAMAGE_MAG</a>
    </td><td>Same as P_DAMAGE but use MAG scalling</td></tr>
    
    <tr><td class="token">
    <a tabindex="-1" href="#" onclick="addToCustomFormula('P_DAMAGE_SPR')">P_DAMAGE_SPR</a>
    </td><td>Same as P_DAMAGE but use SPR scalling</td></tr>
    
    <tr><td class="token">
    <a tabindex="-1" href="#" onclick="addToCustomFormula('M_DAMAGE_SPR')">M_DAMAGE_SPR</a>
    </td><td>Same as M_DAMAGE but use SPR scalling</td></tr>
    
    <tr><td class="token">
    <a tabindex="-1" href="#" onclick="addToCustomFormula('F_DAMAGE_ATK')">F_DAMAGE_ATK</a>
    </td><td>Fixed damage that use ATK scalling</td></tr>
    
    <tr><td class="token">
    <a tabindex="-1" href="#" onclick="addToCustomFormula('P_DAMAGE_MULTICAST')">P_DAMAGE_MULTICAST</a>
    </td><td>Physical damage used with W- or T-ability</td></tr>
    
    <tr><td class="token">
    <a tabindex="-1" href="#" onclick="addToCustomFormula('P_EVADE')">P_EVADE</a>
    </td><td>Physical evade</td></tr>
    
    <tr><td class="token">
    <a tabindex="-1" href="#" onclick="addToCustomFormula('I_PHYSICAL')">I_PHYSICAL</a>
    </td><td>Immunity to physical attacks. This is a shortcut to P_EVADE > 100</td></tr>
    
    <tr><td class="token">
    <a tabindex="-1" href="#" onclick="addToCustomFormula('M_EVADE')">M_EVADE</a>
    </td><td>Magical evade</td></tr>
    
    <tr><td class="token">
    <a tabindex="-1" href="#" onclick="addToCustomFormula('LB')">LB</a>
    </td><td>Number of LB point generated each turn. Note that this number is heavilly dependant on the expected number of LB shards gained per turn.</td></tr>
    
    <tr><td class="token">
    <a tabindex="-1" href="#" onclick="addToCustomFormula('R_FIRE')">R_FIRE</a>, 
    <a tabindex="-1" href="#" onclick="addToCustomFormula('R_ICE')">R_ICE</a>, 
    <a tabindex="-1" href="#" onclick="addToCustomFormula('R_THUNDER')">R_THUNDER</a>, 
    <a tabindex="-1" href="#" onclick="addToCustomFormula('R_WATER')">R_WATER</a>, 
    <a tabindex="-1" href="#" onclick="addToCustomFormula('R_EARTH')">R_EARTH</a>, 
    <a tabindex="-1" href="#" onclick="addToCustomFormula('R_WIND')">R_WIND</a>, 
    <a tabindex="-1" href="#" onclick="addToCustomFormula('R_LIGHT')">R_LIGHT</a>, 
    <a tabindex="-1" href="#" onclick="addToCustomFormula('R_DARK')">R_DARK</a>
    </td><td>Corresponding elemental resistance</td></tr>
    
    <tr><td class="token">
    <a tabindex="-1" href="#" onclick="addToCustomFormula('R_POISON')">R_POISON</a>, 
    <a tabindex="-1" href="#" onclick="addToCustomFormula('R_BLIND')">R_BLIND</a>, 
    <a tabindex="-1" href="#" onclick="addToCustomFormula('R_SLEEP')">R_SLEEP</a>, 
    <a tabindex="-1" href="#" onclick="addToCustomFormula('R_SILENCE')">R_SILENCE</a>, 
    <a tabindex="-1" href="#" onclick="addToCustomFormula('R_PARALYSIS')">R_PARALYSIS</a>, 
    <a tabindex="-1" href="#" onclick="addToCustomFormula('R_CONFUSION')">R_CONFUSION</a>, 
    <a tabindex="-1" href="#" onclick="addToCustomFormula('R_DISEASE')">R_DISEASE</a>, 
    <a tabindex="-1" href="#" onclick="addToCustomFormula('R_PETRIFICATION')">R_PETRIFICATION</a>, 
    <a tabindex="-1" href="#" onclick="addToCustomFormula('R_DEATH')">R_DEATH</a>
    </td><td>Corresponding ailment resistance</td></tr>
    
    <tr><td class="token">
    <a tabindex="-1" href="#" onclick="addToCustomFormula('I_POISON')">I_POISON</a>, 
    <a tabindex="-1" href="#" onclick="addToCustomFormula('I_BLIND')">I_BLIND</a>, 
    <a tabindex="-1" href="#" onclick="addToCustomFormula('I_SLEEP')">I_SLEEP</a>, 
    <a tabindex="-1" href="#" onclick="addToCustomFormula('I_SILENCE')">I_SILENCE</a>, 
    <a tabindex="-1" href="#" onclick="addToCustomFormula('I_PARALYSIS')">I_PARALYSIS</a>, 
    <a tabindex="-1" href="#" onclick="addToCustomFormula('I_CONFUSION')">I_CONFUSION</a>, 
    <a tabindex="-1" href="#" onclick="addToCustomFormula('I_DISEASE')">I_DISEASE</a>, 
    <a tabindex="-1" href="#" onclick="addToCustomFormula('I_PETRIFICATION')">I_PETRIFICATION</a>, 
    <a tabindex="-1" href="#" onclick="addToCustomFormula('I_DEATH')">I_DEATH</a>
    </td><td>Corresponding ailment immunity. I_XXX is a shortcut for R_XXX > 100</td></tr>
    
    <tr><td class="token">
    <a tabindex="-1" href="#" onclick="addToCustomFormula('I_AILMENTS')">I_AILMENTS</a>
    </td><td>Immunity to all ailments. This condition is a shortcut for all R_&lt;ailment&gt; > 100</td></tr>
    
    <tr><td class="token">
    <a tabindex="-1" href="#" onclick="addToCustomFormula('I_DISABLE')">I_DISABLE</a>
    </td><td>Immunity to all disabling ailments. This condition is a shortcut for I_SLEEP; I_PARALYSIS; I_CONFUSION; I_PETRIFICATION</td></tr>
    
    <tr><td class="token">
    <a tabindex="-1" href="#" onclick="addToCustomFormula('E_FIRE')">E_FIRE</a>, 
    <a tabindex="-1" href="#" onclick="addToCustomFormula('E_ICE')">E_ICE</a>, 
    <a tabindex="-1" href="#" onclick="addToCustomFormula('E_THUNDER')">E_THUNDER</a>, 
    <a tabindex="-1" href="#" onclick="addToCustomFormula('E_WATER')">E_WATER</a>, 
    <a tabindex="-1" href="#" onclick="addToCustomFormula('E_EARTH')">E_EARTH</a>, 
    <a tabindex="-1" href="#" onclick="addToCustomFormula('E_WIND')">E_WIND</a>, 
    <a tabindex="-1" href="#" onclick="addToCustomFormula('E_LIGHT')">E_LIGHT</a>, 
    <a tabindex="-1" href="#" onclick="addToCustomFormula('E_DARK')">E_DARK</a>
    </td><td>Those special conditions will force the resulting build to have the corresponding element(s) and no other elements</td></tr>
    
    <tr><td class="token">
    <a tabindex="-1" href="#" onclick="addToCustomFormula('E_NONE')">E_NONE</a>
    </td><td>Force a none elemental build. This condition is not compatible with E_FIRE, E_ICE, ...</td></tr>
    </tbody>

**Comment by lyrgard** [comment]
I'm thinking of creating a new page for all this help. Your write up is really good, I'll use it a lot !

I'll also try the buttons. I'm still hesitating between something like you did (that adds to the input field) or a formulary where the user can input their criteria with checkboxes.
