### ISSUE TITLE
Condition Not Meet pinned materia are not correctly re-evaluated at build time

### ISSUE THREAD

**Issue by lyrgard** [lyrgard/ffbeEquip#91]
I was building Sephiroth for Physical Damage (not logged in, all gear), set light/dark resist to -100, and forced SSP-Dark in the top right materia slot, and got a build that added a second SSP-Dark in the bottom left materia slot (build can't share because it is a non-stacking materia)(modifié)
I noticed that when you pin SSP-Dark, it doesn't have the non-stacking icon, not sure if that is relevant
Looks like it happens with many non-stacking materia, when you pin them to an otherwise empty sheet

**Comment by tomurderthelight** [comment]
this looks like it's the same issue as pinned masteries is having. i hadn't considered checking the 'stackable' icon when i went through that, but now that i go back and look, that icon disappears and reappears with the bonus notations when certain materia are pinned or unpinned.

**Comment by lyrgard** [comment]
Corrected
